# SPDX-FileCopyrightText: 2020 The cython-iscsi Authors
#
# SPDX-License-Identifier: MIT

dist: bionic

language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
      env: PRE_COMMIT=true
    - python: 3.9-dev
      env: RUN_MYPY=false

install:
  - pip install .[dev]

addons:
  apt:
    packages:
      - libiscsi-dev

script:
  - pytest
  - if [[ $PRE_COMMIT ]]; then pre-commit install; pre-commit run --all-files; fi
